module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        "cta-blue": "var(--cta-blue)",
        "deep-gray": "var(--deep-gray)",
        "errorerror-500": "var(--errorerror-500)",
        gray: "var(--gray)",
        "graygray-200": "var(--graygray-200)",
        "graygray-300": "var(--graygray-300)",
        "graygray-500": "var(--graygray-500)",
        "graygray-600": "var(--graygray-600)",
        "graygray-800": "var(--graygray-800)",
        "graygray-900": "var(--graygray-900)",
        "light-gray": "var(--light-gray)",
        "main-black": "var(--main-black)",
        "main-white": "var(--main-white)",
        "main-yellow": "var(--main-yellow)",
        "mid-gray": "var(--mid-gray)",
        "mid-grey": "var(--mid-grey)",
        "sec-green": "var(--sec-green)",
        "semi-gray": "var(--semi-gray)",
        stone: "var(--stone)",
        "stroke-card": "var(--stroke-card)",
        "theme-card-fill": "var(--theme-card-fill)",
        "theme-card-stroke": "var(--theme-card-stroke)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-medium": "var(--body-medium-font-family)",
        "footnote-regular": "var(--footnote-regular-font-family)",
        "h4-medium": "var(--h4-medium-font-family)",
        "h5-semibold": "var(--h5-semibold-font-family)",
        "type-face-b3-regular": "var(--type-face-b3-regular-font-family)",
        "type-face-b4-semibold": "var(--type-face-b4-semibold-font-family)",
        "type-face-b7-regular": "var(--type-face-b7-regular-font-family)",
        "type-face-b7-semibold": "var(--type-face-b7-semibold-font-family)",
        "type-face-b8-regular": "var(--type-face-b8-regular-font-family)",
        "type-face-b9-regular": "var(--type-face-b9-regular-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "bgblur-sm-dark": "var(--bgblur-sm-dark)",
        "deep-card": "var(--deep-card)",
        "shadow-2xl": "var(--shadow-2xl)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
